DROP TABLE IF EXISTS
roles,
role_permissions,
permissions,
users,
user_permissions,
user_court_access,
user_presence,
user_activity_logs,
courts,
judges,
cases,
data_access_policies,
retention_policies,
security_incidents,
dockets,
case_history,
case_transfers,
documents,
hearings,
entity_relationships,
parties,
case_parties,
case_documents,
scheduling_orders,
discovery,
pleadings,
motions,
pretrial_conferences,
judgments,
appeals,
notifications,
activity_logs,
fees_payments,
user_actions,
user_frequent_actions,
user_last_actions,
chat_rooms,
messages,
chat_participants,
chat_notifications,
chat_files,
message_threads,
message_reactions,
chat_audit_logs,
case_assignments,
case_tags,
related_cases,
electronic_signatures,
document_access_logs,
case_schedules,
legal_citations,
case_status_history,
case_flags,
failed_operations,
document_versions,
court_calendar,
sealed_documents,
cases_2019,
cases_2020,
cases_2021,
cases_2022,
cases_2023,
cases_2024,
cases_2025
CASCADE;


do $$ declare
    r record;
begin
    for r in (select tablename from pg_tables where schemaname = 'app-db') loop
        execute 'drop table if exists ' || quote_ident(r.tablename) || ' cascade';
    end loop;
end $$;
