# Format code - 'cargo make fmt'
[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

# Clean - 'cargo make clean'
[tasks.clean]
command = "cargo"
args = ["clean"]

# Unix/Mac build - 'cargo make up'
[tasks.up]
command = "sh"
args = ["-c", "LEPTOS_OUTPUT_NAME=lexodus spin up --build"]
dependencies = ["clean"]

# Windows build - 'cargo make up-win'
[tasks.up-win]
command = "powershell"
args = ["-Command", "$env:LEPTOS_OUTPUT_NAME='lexodus'; spin up --build"]
dependencies = ["clean"]

# Test - 'cargo make test'
[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# Drop database - 'cargo make db-drop'
[tasks.db-drop]
command = "sqlx"
args = ["database", "drop", "-y"]

# Create database - 'cargo make db-create'
[tasks.db-create]
command = "sqlx"
args = ["database", "create"]

# Run migrations - 'cargo make db-migrate'
[tasks.db-migrate]
command = "sqlx"
args = ["migrate", "run"]

# Add new migration - 'cargo make db-new-migration'
[tasks.db-new-migration]
command = "sqlx"
args = ["migrate", "add", "${@}"]

# Reset database (drop, create, migrate) - 'cargo make db-reset'
[tasks.db-reset]
dependencies = ["db-drop", "db-create", "db-migrate"]

# Check database - 'cargo make db-check'
[tasks.db-check]
command = "sqlx"
args = ["database", "check"]

# Prepare SQLx - 'cargo make db-prepare'
[tasks.db-prepare]
command = "sqlx"
args = ["prepare", "--", "--all-features"]

# Full database setup for development - 'cargo make db-setup'
[tasks.db-setup]
dependencies = ["db-reset", "db-prepare"]

# Add database tasks to the main run commands
[tasks.run]
dependencies = [
    "fmt",
    "db-setup",
    "up",
    "test"
]

[tasks.run-win]
dependencies = [
    "fmt",
    "db-setup",
    "up-win",
    "test"
]

# Unix/Mac dev mode - 'cargo make watch'
[tasks.watch]
dependencies = ["clean"]
command = "sh"
args = ["-c", "LEPTOS_OUTPUT_NAME=lexodus spin watch"]

# Windows dev mode - 'cargo make watch-win'
[tasks.watch-win]
dependencies = ["clean"]
command = "powershell"
args = ["-Command", "$env:LEPTOS_OUTPUT_NAME='lexodus'; spin watch"]

# Unix/Mac deploy - 'cargo make deploy'
[tasks.deploy]
dependencies = ["clean", "up"]
command = "sh"
args = ["-c", "LEPTOS_OUTPUT_NAME=lexodus spin deploy"]

# Windows deploy - 'cargo make deploy-win'
[tasks.deploy-win]
dependencies = ["clean", "up-win"]
command = "powershell"
args = ["-Command", "$env:LEPTOS_OUTPUT_NAME='lexodus'; spin deploy"]
