spin_manifest_version = 2

[application]
name = "lexodus"
version = "0.1.0"
authors = ["Tyler Harpool <tylerharpool@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "lexodus"

[variables]
secret = { default = "Hello, Lexodusian", required = false }
dev = { default = "version: 0.1.0", required = false }

[component.lexodus]
source = "target/wasm32-wasi/release/lexodus.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.lexodus.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=lexodus cargo build --lib --target wasm32-wasi --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "pkg"


[component.pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]


[component.lexodus.variables]
token = "{{ secret }}"
dev_value = "{{dev}}"
