name: Deploy

# Deploy only when a change is pushed or merged to `main`
on:
  push:
    branches:
      - main

jobs:
  spin:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip1 wasm32-unknown-unknown

      - name: Setup cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Cargo generate-lockfile
        run: cargo generate-lockfile

      - uses: Swatinem/rust-cache@v2

      - name: Install binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Cargo Component
        run: cargo binstall cargo-component --no-confirm

      - name: Install wasm-bindgen
        run: cargo binstall wasm-bindgen-cli --no-confirm

      - name: Install cargo-leptos
        run: cargo binstall cargo-leptos --no-confirm


      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1

      - name: Build and deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          variables: |-
            db_url=${{ secrets.DB_URL }}
            turso_token=${{ secrets.TURSO_TOKEN }}
            turso_url=${{ secrets.TURSO_URL }}
